FEATURE_LIST = [
    {
        "FEATURE_NAME": "avfortisandbox",
        "test_case_folder": ["testcase", "testcase_v1"],
        "test_config": ["env.newman.FGT_KVM.avfortisandbox.conf"],
        "test_groups": ["grp.avfortisandbox_fortistack.full", "grp.avfortisandbox_fortistack.short"],
        "docker_compose": ["docker.avfortisandbox_avfortisandbox.yml", "other"],
        "email": ["yzhengfeng@fortinet.com,vlysak@fortinet.com"],
    },
    {
        "FEATURE_NAME": "webfilter",
        "test_case_folder": ["testcase_v1", "testcase"],
        "test_config": ["env.FGTVM64.webfilter_demo.conf"],
        "test_groups": [
            "grp.webfilter_basic.full",
            "grp.webfilter_basic2.full",
            "grp.webfilter_ha.full",
            "grp.webfilter_flow.full",
            "grp.webfilter_peruser.full",
            "grp.webfilter_onearm.full",
            "grp.webfilter_other.full",
            "grp.webfilter_other2.full",
        ],
        "docker_compose": ["docker.webfilter_basic.yml", "other"],
        "email": ["hchuanjian@fortinet.com"],
    },
    {
        "FEATURE_NAME": "avenregres",
        "test_case_folder": ["testcase_v1", "testcase"],
        "test_config": ["env.FGTVM64.avenregres_demo.conf"],
        "test_groups": ["grp.avenregres.full"],
        "docker_compose": ["docker.avenregres_avenregres.yml", "other"],
        "email": ["hchuanjian@fortinet.com"],
    },
    {
        "FEATURE_NAME": "dnsfilter",
        "test_case_folder": ["testcase", "testcase_v1"],
        "test_config": ["env.FGTVM64_dnsfilter_fortistack.conf"],
        "test_groups": ["grp.dnsfilter_fortistack.crit", "grp.dnsfilter.crit", "grp.dnsfilter.full"],
        "docker_compose": ["docker.dnsfilter_dnsfilter.yml", "other"],
        "email": ["vlysak@fortinet.com"],
    },
    {
        "FEATURE_NAME": "threatfeed",
        "test_case_folder": ["testcase_v1"],
        "test_config": ["env.fortistack.threatfeed.conf"],
        "test_groups": ["grp.threatfeed.full"],
        "docker_compose": ["KVM"],
        "email": ["yzhengfeng@fortinet.com,wangd@fortinet.com"],
        "PROVISION_VMPC": true,
        "VMPC_NAMES": "VMPC1,VMPC4",
        "PROVISION_DOCKER": false,
    },
    {
        "FEATURE_NAME": "antivirus",
        "test_case_folder": ["testcase_v1"],
        "test_config": ["env.fortistack.antivirus.conf"],
        "test_groups": [
            "grp.antivirus_proxy.full",
            "grp.antivirus_proxy_ipv6.full",
            "grp.antivirus_webproxy.full",
            "grp.antivirus_sdwan.full",
            "grp.antivirus_misc.full",
            "grp.antivirus_tp.full",
            "grp.antivirus_tp_ipv6.full",
            "grp.antivirus_wanopt.full",
            "grp.antivirus_flow.full",
            "grp.antivirus_flow_ipv6.full",
            "grp.antivirus_ngfw.full",
            # "grp.antivirus_snifint.full", #Not supported well in AIO test bed
            "grp.antivirus_ha.full",
        ],
        "docker_compose": ["docker.antivirus_proxy.yml", "other"],
        "email": ["lluo@fortinet.com"],
    },
    {
        "FEATURE_NAME": "avaimodel",
        "test_case_folder": ["testcase_v1"],
        "test_config": ["env.fortistack.avaimodel.conf"],
        "test_groups": ["grp.avaimodel.full"],
        "docker_compose": ["docker.avaimodel_proxy.yml", "other"],
        "email": ["lluo@fortinet.com"],
    },
    {
        "FEATURE_NAME": "wanopt",
        "test_case_folder": ["testcase"],
        "test_config": ["env.fortistack.wanopt.conf"],
        "test_groups": ["grp.wanopt.fortistack.crit", "grp.wanopt.fortistack.full"],
        "docker_compose": ["docker.wanopt_linux.yml", "other"],
        "email": ["wangt@fortinet.com"],
    },
    {
        "FEATURE_NAME": "webcache",
        "test_case_folder": ["testcase"],
        "test_config": ["env.fortistack.webcache.conf"],
        "test_groups": ["grp.webcache.fortistack.crit", "grp.webcache.fortistack.full"],
        "docker_compose": ["docker.webcache_webcache.yml", "other"],
        "email": ["wangt@fortinet.com"],
    },
    {
        "FEATURE_NAME": "icap",
        "test_case_folder": ["testcase"],
        "test_config": ["env.fortistack.icap.conf"],
        "test_groups": ["grp.icap.fortistack.crit", "grp.icap.fortistack.full"],
        "docker_compose": ["docker.icap_icap.yml", "other"],
        "email": ["wangt@fortinet.com"],
    },
    {
        "FEATURE_NAME": "webproxy",
        "test_case_folder": ["testcase"],
        "test_config": ["env.fortistack.webproxy.conf"],
        "test_groups": [
            "grp.webproxy_auth_fortistack.full",
            "grp.webproxy_basic_fortistack.full",
            "grp.webproxy_forward_fortistack.full",
            "grp.webproxy_policy_fortistack.full",
            "grp.webproxy_topology_fortistack.full",
        ],
        "docker_compose": ["docker.webproxy_webproxy.yml", "other"],
        "email": ["zachwang@fortinet.com"],
    },
    {
        "FEATURE_NAME": "ftpproxy",
        "test_case_folder": ["testcase"],
        "test_config": ["env.fortistack.ftpproxy.conf"],
        "test_groups": ["grp.ftpproxy_fortistack.full"],
        "docker_compose": ["docker.ftpproxy_ftpproxy.yml", "other"],
        "email": ["zachwang@fortinet.com"],
    },
    {
        "FEATURE_NAME": "sslprofile",
        "test_case_folder": ["testcase_v1"],
        "test_config": ["env.fortistack.sslprofile_proxy.conf"],
        "test_groups": [
            "grp.sslprofile_proxy.crit",
            "grp.sslprofile_proxy.sub01.full",
            "grp.sslprofile_proxy.sub02.full",
            "grp.sslprofile_proxy.sub03.full",
            "grp.sslprofile_proxy.sub04.full",
        ],
        "docker_compose": ["docker.sslprofile_proxy.yml", "other"],
        "email": ["YUZHU@fortinet.com"],
    },
    {
        "FEATURE_NAME": "foc",
        "test_case_folder": ["testcase_v1"],
        "test_config": ["env.foc.fortistack.conf"],
        "test_groups": ["grp.foc_gtp.fstack.full", "grp.foc_gtp_ha.fstack.full", "grp.foc_gtp_s10.fstack.full", "grp.foc_pfcp.fstack.full"],
        "docker_compose": ["docker.foc_gtp.yml", "other"],
        "email": ["wangt@fortinet.com,mabbasi@fortinet.com"],
    },
    {
        "FEATURE_NAME": "sslprofile",
        "test_case_folder": ["testcase_v1"],
        "test_config": ["env.fortistack.sslprofile_flow.conf"],
        "test_groups": ["grp.sslprofile_flow.crit", "grp.sslprofile_flow.full"],
        "docker_compose": ["docker.sslprofile_flow.yml", "other"],
        "email": ["eson@fortinet.com"],
    },
    {
        "FEATURE_NAME": "waf",
        "test_case_folder": ["testcase_v1"],
        "test_config": ["env.fstack.waf.conf"],
        "test_groups": ["grp.waf.fstack.full"],
        "docker_compose": ["docker.waf_waf.yml", "other"],
        "email": ["mabbasi@fortinet.com"],
    },
    {
        "FEATURE_NAME": "dlp",
        "test_case_folder": ["testcase_v1"],
        "test_config": ["env.fortistack.dlp.conf"],
        "test_groups": [
            "grp.dlp_exproxy.full",
            "grp.dlp_flowbase.full",
            "grp.dlp_ha.full",
            "grp.dlp_interface.full",
            "grp.dlp_language.full",
            "grp.dlp_nat1.full",
            "grp.dlp_nat2.full",
            "grp.dlp_tp.full",
            "grp.dlp_wanopt.full",
        ],
        "docker_compose": ["docker.dlp_nat1.yml", "other"],
        "email": ["yjiaran@fortinet.com"],
    },
    {
        "FEATURE_NAME": "servicedatabase",
        "test_case_folder": ["testcase_v1"],
        "test_config": ["env.servicedatabase_fortistack.conf"],
        "test_groups": ["grp.servicedatabase.crit"],
        "docker_compose": ["docker.servicedatabase_servicedatabase.yml", "other"],
        "email": ["yjiaran@fortinet.com"],
    },
    {
        "FEATURE_NAME": "avfortindr",
        "test_case_folder": ["testcase"],
        "test_config": ["env.FGT_KVM.avfortindr.conf"],
        "test_groups": ["grp.avfortindr_fortistack.full"],
        "docker_compose": ["docker.avfortindr_avfortindr.yml", "other"],
        "email": ["vlysak@fortinet.com"],
    },
    {
        "FEATURE_NAME": "filefilter",
        "test_case_folder": ["testcase_v1"],
        "test_config": ["env.fortistack.filefilter.conf"],
        "test_groups": ["grp.filefilter.full"],
        "docker_compose": ["docker.filefilter_filefilter.yml", "other"],
        "email": ["yshang@fortinet.com"],
    },
    {
        "FEATURE_NAME": "videofilter",
        "test_case_folder": ["testcase_v1"],
        "test_config": ["env.fortistack.videofilter.conf"],
        "test_groups": ["grp.videofilter.full"],
        "docker_compose": ["docker.videofilter_videofilter.yml", "other"],
        "email": ["yshang@fortinet.com"],
    },
]
