# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Skip these files
exclude: "^\
  (third-party/.*)\
  "

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files # prevents giant files from being committed.
      - id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems.
      # - id: check-executables-have-shebangs # ensures that (non-binary) executables have a shebang.
      - id: check-json # checks json files for parseable syntax.
      - id: check-shebang-scripts-are-executable # ensures that (non-binary) files with a shebang are executable.
      - id: check-merge-conflict # checks for files that contain merge conflict strings.
      - id: check-symlinks # checks for symlinks which do not point to anything.
      - id: check-yaml # checks yaml files for parseable syntax.
      - id: destroyed-symlinks # detects symlinks which are changed to regular files with a content of a path which that symlink was pointing to.
      - id: detect-private-key # detects the presence of private keys.
      - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline.
      - id: file-contents-sorter # sorts the lines in specified files (defaults to alphabetical). you must provide list of target files as input in your .pre-commit-config.yaml file.
      - id: fix-byte-order-marker # removes utf-8 byte order marker.
      - id: mixed-line-ending # replaces or checks mixed line ending.
      - id: requirements-txt-fixer # sorts entries in requirements.txt.
      - id: trailing-whitespace # trims trailing whitespace.

  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: ''
  #   hooks:
  #     - id: prettier
  #       language_version: system  # use system's Node
  #       files: \.(js|ts|jsx|tsx|css|less|html|json|markdown|md|yaml|yml)$
  #       # Below line tells nodeenv to skip autodetect and install Node 18.17.1
  #       # args: ["--node=18.17.1", "--prebuilt"]

  # Autoflake repository
  - repo: https://github.com/myint/autoflake
    rev: v2.2.1 # Replace with the desired version of autoflake
    hooks:
      - id: autoflake
        args: [--in-place, --remove-unused-variables]
        # additional_dependencies: ['flake8==3.9.2']  # Optional: specify specific flake8 version

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args: ["--line-length=180"]

  # - repo: local
  #   hooks:
  #     - id: black
  #       name: black
  #       entry: black
  #       language: system
  #       types: [python]
  #       args: ["--line-length=180"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black]

  # - repo: https://github.com/PyCQA/pylint
  #   rev: v3.0.1
  #   hooks:
  #     - id: pylint

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ["--max-line-length=180"]

  # - repo: https://github.com/PyCQA/pylint
  #   rev: v3.0.1  # or whichever version you want
  #   hooks:
  #     - id: pylint
  #       # Let pre-commit manage an isolated environment:
  #       language: python
  #       types: [python]
  #       args: ["--max-line-length=180"]
  #       # Pin your pylint version so it's consistent across devs/CI:
  #       additional_dependencies: [ "pylint==3.0.1" ]


  # - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
  #   rev: v0.1.0
  #   hooks:
  #     - id: dockerfilelint
  #       language_version: system

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
