services:
  jenkins-master:
    build:
      context: /home/fosqa/jenkins-master
      dockerfile: Dockerfile.jenkins
      network: host
    container_name: jenkins-master
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
      - "443:8443"
    environment:
      JAVA_OPTS: >-
        -Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
        -Duser.timezone=America/Vancouver
        -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=86400
        -Dhudson.model.DirectoryBrowserSupport.CSP=""
      JENKINS_OPTS: >-
        --httpPort=8080
        --httpsPort=8443
        --httpsKeyStore=/var/jenkins_home/jenkins.jks
        --httpsKeyStorePassword=changeit
      # DISABLED: JCasC configuration (will configure SAML manually)
      # CASC_JENKINS_CONFIG: /var/jenkins_home/casc_configs/jenkins-saml.yaml
      JENKINS_KEYSTORE_PASSWORD: changeit
    volumes:
      - jenkins_data:/var/jenkins_home
      - /home/fosqa/jenkins-master/jenkins.jks:/var/jenkins_home/jenkins.jks:ro
      - /home/fosqa/jenkins-master:/home/fosqa/jenkins-master
      - /home/fosqa/resources/tools:/home/fosqa/resources/tools
      - /home/fosqa/jenkins-master/feature-configs:/var/jenkins_home/feature-configs:ro
      - /home/fosqa/known_hosts:/var/jenkins_home/.ssh/known_hosts:ro
      # Mount init.groovy.d for local admin creation
      - /home/fosqa/jenkins-master/init.groovy.d:/var/jenkins_home/init.groovy.d:ro
      # Keep jcasc directory mounted (we'll use idp-metadata.xml file from here)
      - /home/fosqa/jenkins-master/jcasc:/var/jenkins_home/casc_configs:ro
    networks:
      - custom_network
    extra_hosts:
      - "dockerhost:192.168.99.1"

volumes:
  jenkins_data:

networks:
  custom_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.99.0/24
          gateway: 192.168.99.1
