services:
  jenkins-master:
    build:
      context: /home/fosqa/jenkins-master
      dockerfile: Dockerfile.jenkins
    container_name: jenkins-master
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true -Duser.timezone=America/Vancouver
    volumes:
      - jenkins_data:/var/jenkins_home
      - /home/fosqa/jenkins-master:/home/fosqa/jenkins-master
      - /home/fosqa/resources/tools:/home/fosqa/resources/tools
      - /home/fosqa/jenkins-master/feature-configs:/var/jenkins_home/feature-configs:ro
      - /home/fosqa/known_hosts:/var/jenkins_home/.ssh/known_hosts:ro
    networks:
      - custom_network

volumes:
  jenkins_data:

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.99.0/24
