services:
  jenkins-master:
    build:
      context: /home/fosqa/jenkins-master
      dockerfile: Dockerfile.jenkins
      network: host  # Fix for apt-get and pip network issues during build
    container_name: jenkins-master
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
      - "443:8443"
    environment:
      # map-style; preserves it as one variable
      JAVA_OPTS: >-
        -Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
        -Duser.timezone=America/Vancouver
        -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=86400
        -Dhudson.model.DirectoryBrowserSupport.CSP=""
      JENKINS_OPTS: >-
        --httpPort=8080
        --httpsPort=8443
        --httpsKeyStore=/var/jenkins_home/jenkins.jks
        --httpsKeyStorePassword=changeit
    volumes:
      - jenkins_data:/var/jenkins_home
      # - /home/fosqa/jenkins-master/QA_All_In_Certificate_2025_passUpdated.p12:/var/jenkins_home/jenkins.p12:ro
      - /home/fosqa/jenkins-master/jenkins.jks:/var/jenkins_home/jenkins.jks:ro
      # - /home/fosqa/jenkins-master/init.groovy.d:/var/jenkins_home/init.groovy.d:ro
      - /home/fosqa/jenkins-master:/home/fosqa/jenkins-master
      - /home/fosqa/resources/tools:/home/fosqa/resources/tools
      - /home/fosqa/jenkins-master/feature-configs:/var/jenkins_home/feature-configs:ro
      - /home/fosqa/known_hosts:/var/jenkins_home/.ssh/known_hosts:ro
    networks:
      - custom_network

volumes:
  jenkins_data:

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.99.0/24
