services:
  jenkins-master:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    environment: #let jenkins accept local git repo
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
    volumes:
      - jenkins_data:/var/jenkins_home
      - /home/fosqa/jenkins-master:/home/fosqa/jenkins-master
    networks:
      - custom_network

volumes:
  jenkins_data:

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.99.0/24
