services:
  jenkins-master:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    restart: unless-stopped
    ports:
      - "8080:8080"      # Jenkins UI
      - "50000:50000"    # Inbound agent port
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - custom_network

volumes:
  jenkins_data:

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.99.0/24